#ifndef _ENUMS_
#define _ENUMS_

typedef enum CameraId {
	CAMERA_OFFSCREEN = 0,
	CAMERA_OFFSCREEN2,
	CAMERA_SHADOW,
	CAMERA_BACKGROUND,
	CAMERA_3D,
	CAMERA_3D_EFFECTA,
	CAMERA_3D_IMAGE,
	CAMERA_3D_EFFECTB,
	CAMERA_2D,
	CAMERA_FADE,
	CAMERA_FADE2,
	CAMERA_DEBUG,
	CAMERA_DEBUG_3D
} CameraId;

#endif //_ENUMS_