#!/usr/bin/env python3
"""
Parses .obj/.endobj assembly blocks into C89 BattleUnitSetup array definitions.

Usage:
    python3 parse_battle_unit_setup.py <input.s> [output.c]
    (if output.c is omitted, prints to stdout)

struct layout (0x30 bytes, big-endian target):
    0x00  BattleUnitKind*  unit_kind_params
    0x04  s8               ally_status
    0x05  u8               _pad0[3]
    0x08  s32              attack_phase
    0x0c  Vec              position
    0x18  u32              addl_target_offset_x
    0x1c  u32              battle_unit_work[4]
    0x2c  ItemDropData*    item_drop_table
    0x30  (end)
"""

import re
import struct
import sys

WORDS_PER_STRUCT = 12  # 0x30 / 4


def ieee754_to_float(u32):
    return struct.unpack('>f', struct.pack('>I', u32))[0]


def fmt_float(f):
    """Format a float as a C literal (always includes decimal point)."""
    if f == int(f) and abs(f) < 1e15:
        return "%.1ff" % f
    return "%sf" % repr(f)


def parse_word(token):
    """Returns (int_value_or_None, symbol_or_None)."""
    token = token.strip()
    if re.match(r'^0[xX][0-9a-fA-F]+$', token):
        return (int(token, 16), None)
    if re.match(r'^-?\d+$', token):
        return (int(token), None)
    return (None, token)


def parse_text(text):
    """Returns list of (obj_name, [[word_tuple * 12], ...]) per .obj block."""
    results = []
    obj_re = re.compile(
        r'\.obj\s+(\w+),\s*\w+\s*(.*?)\.endobj\s+\1',
        re.DOTALL
    )
    fb_re = re.compile(r'\.4byte\s+(\S+)')

    for m in obj_re.finditer(text):
        name = m.group(1)
        body = m.group(2)
        words = [parse_word(t.group(1)) for t in fb_re.finditer(body)]

        if len(words) % WORDS_PER_STRUCT != 0:
            sys.stderr.write(
                "WARNING: %s has %d words, not a multiple of %d; "
                "trailing words ignored.\n" % (name, len(words), WORDS_PER_STRUCT)
            )

        structs = []
        n = len(words) // WORDS_PER_STRUCT
        for i in range(n):
            structs.append(words[i * WORDS_PER_STRUCT:(i + 1) * WORDS_PER_STRUCT])
        results.append((name, structs))

    return results


def collect_externs(objects):
    """Gather unique symbol references. Returns (unit_kind_syms, item_drop_syms)."""
    unit_kind_syms = []
    item_drop_syms = []
    seen_uk = set()
    seen_id = set()

    for _name, structs in objects:
        for w in structs:
            if w[0][1] and w[0][1] not in seen_uk:
                seen_uk.add(w[0][1])
                unit_kind_syms.append(w[0][1])
            if w[11][1] and w[11][1] not in seen_id:
                seen_id.add(w[11][1])
                item_drop_syms.append(w[11][1])

    return unit_kind_syms, item_drop_syms


def word_to_ptr(word):
    """For pointer fields: symbol name, NULL, or cast from hex."""
    if word[1]:
        return "&%s" % word[1]
    if word[0] == 0:
        return "NULL"
    return "(void*)0x%08XU" % word[0]


def emit_struct_initializer(w, indent="        "):
    lines = []

    # 0x00  BattleUnitKind* unit_kind_params
    lines.append("%s/* 0x00 */ %s," % (indent, word_to_ptr(w[0])))

    # 0x04  s8 ally_status  (big-endian: lives in MSB of the raw word)
    raw_ally = w[1][0] if w[1][0] is not None else 0
    ally_status = (raw_ally >> 24) & 0xFF
    if ally_status >= 0x80:
        ally_status -= 0x100
    lines.append("%s/* 0x04 */ %d," % (indent, ally_status))

    # 0x05  u8 _pad0[3]
    lines.append("%s/* 0x05 */ { 0, 0, 0 }," % indent)

    # 0x08  s32 attack_phase
    attack_phase = w[2][0] if w[2][0] is not None else 0
    lines.append("%s/* 0x08 */ 0x%08X," % (indent, attack_phase & 0xFFFFFFFF))

    # 0x0c  Vec position  (x, y, z as floats)
    px = ieee754_to_float(w[3][0] if w[3][0] is not None else 0)
    py = ieee754_to_float(w[4][0] if w[4][0] is not None else 0)
    pz = ieee754_to_float(w[5][0] if w[5][0] is not None else 0)
    lines.append("%s/* 0x0c */ { %s, %s, %s }," % (
        indent, fmt_float(px), fmt_float(py), fmt_float(pz)
    ))

    # 0x18  u32 addl_target_offset_x
    off_x = w[6][0] if w[6][0] is not None else 0
    lines.append("%s/* 0x18 */ 0x%08XU," % (indent, off_x))

    # 0x1c  u32 battle_unit_work[4]
    buw = []
    for i in range(4):
        v = w[7 + i][0] if w[7 + i][0] is not None else 0
        buw.append("0x%08XU" % v)
    lines.append("%s/* 0x1c */ { %s }," % (indent, ", ".join(buw)))

    # 0x2c  ItemDropData* item_drop_table
    lines.append("%s/* 0x2c */ %s," % (indent, word_to_ptr(w[11])))

    return lines


HEADER = """\
/* Auto-generated by parse_battle_unit_setup.py -- do not edit by hand. */

#include "types.h"
#include "battle/battle_unit.h"
#include "battle/item_drop.h"

"""

STRUCT_DEF = """\
typedef struct BattleUnitSetup {
    /* 0x00 */ BattleUnitKind* unit_kind_params;
    /* 0x04 */ s8              ally_status;
    /* 0x05 */ u8              _pad0[3];
    /* 0x08 */ s32             attack_phase;
    /* 0x0c */ Vec             position;
    /* 0x18 */ u32             addl_target_offset_x;
    /* 0x1c */ u32             battle_unit_work[4];
    /* 0x2c */ ItemDropData*   item_drop_table;
    /* 0x30 */
} BattleUnitSetup; /* size = 0x30 */

"""


def generate_c(objects):
    out = []
    out.append(HEADER)
    out.append(STRUCT_DEF)

    unit_kind_syms, item_drop_syms = collect_externs(objects)

    if unit_kind_syms or item_drop_syms:
        out.append("/* External symbol declarations */\n")
    for sym in unit_kind_syms:
        out.append("extern BattleUnitKind %s;\n" % sym)
    if unit_kind_syms:
        out.append("\n")
    for sym in item_drop_syms:
        out.append("extern ItemDropData %s[];\n" % sym)
    if item_drop_syms:
        out.append("\n")

    for obj_name, structs in objects:
        count = len(structs)
        out.append("BattleUnitSetup %s[%d] = {\n" % (obj_name, count))
        for i, w in enumerate(structs):
            out.append("    {\n")
            for line in emit_struct_initializer(w):
                out.append(line + "\n")
            comma = "," if i < count - 1 else ""
            out.append("    }%s\n" % comma)
        out.append("};\n\n")

    return "".join(out)


def main():
    if len(sys.argv) < 2:
        sys.stderr.write("Usage: %s <input.s> [output.c]\n" % sys.argv[0])
        sys.exit(1)

    with open(sys.argv[1], 'r') as f:
        text = f.read()

    objects = parse_text(text)
    if not objects:
        sys.stderr.write("No .obj blocks found in input.\n")
        sys.exit(1)

    c_code = generate_c(objects)

    if len(sys.argv) >= 3:
        with open(sys.argv[2], 'w') as f:
            f.write(c_code)
        sys.stderr.write("Wrote %s\n" % sys.argv[2])
    else:
        sys.stdout.write(c_code)


if __name__ == '__main__':
    main()
